### ISSUE TITLE
4754460 is probably a secondary eclipse

### ISSUE THREAD

**Issue by dfm** [dfm/peerless#10]
As I mention at the end of Section 3.3, KIC 4754460 is probably the secondary eclipse of an EB system. There is a deep half eclipse right at the end of the mission that was automatically found in earlier versions of the code but the final version isn't flagged because it is too close to the beginning of the quarter. A diagnostic plot showing the eclipse is attached below. The question is: what should we do about this? I think that it's probably best to just do some sort of accounting for it in @timothydmorton's simulations of FP populations but we could also just comment on how the results change if we remove it by hand.

@timothydmorton: any thoughts?

![0001-3](https://cloud.githubusercontent.com/assets/350282/16846294/2485524a-49ec-11e6-8882-5ed2355bb759.png)

**Comment by timothydmorton** [comment]
My prediction is that each candidate has a few % FPP (varying from 2% to 20%), with the exception of 9306307 and 10602068, which I predict to be almost certainly EBs (though to be fair this is probably mostly because my planet simulations only go up to 1 Rjup).  So apart from those two, I predict about a 50% chance that at least one of the others is a false positive, so I can discuss this is in the section.  It would probably be a good idea to also say how much the results change if that one is taken out.

**Comment by dfm** [comment]
I think we're good on this one now.
