### ISSUE TITLE
Other to do items before submission

### ISSUE THREAD

**Issue by dfm** [dfm/peerless#12]
- [x] Discuss prospects for RV and astrometry follow-up
- [x] Quantitatively compare to other survey results
- [x] ~~Add a corner plot to the section about parameter estimation~~
- [ ] ~~Discuss potential for the discovery of moons, rings, Trojans, etc.~~

From Tim:
- [x] Label the y-axis of the signals in Figure 1
- [x] Include some discussion about the potential scientific interest of the "box" signals. Some of these could very well be secondary eclipses of WDs, that would be super-easy to find with a very modest level of RV follow-up! For how many signals is the box model is the best explanation? These might even be worth a separate table.
- [x] Label the units of the y-axis (at least in the first column) in Figure 3.
- [x] In the OR section (or conclusion), mention/discuss the implied integrated occurrence rate over the two bins---something like 1.5-2 planets per star? This is interesting because (a) the Solar System has 2, and (b) it maybe jives with microlensing searches finding lots of sub-Jupiters on longer periods (would need to check references for this)? This is good to connect with because most people don't have intuition for a differential rate in log units.
- [x] Table 6 should also have the epoch, as well as the period, for observers' convenience.

Finally:
- [x] Find place online to share MCMC chains
- [x] Send to co-authors for comments
- [ ] Send to friends for comments

**Comment by timothydmorton** [comment]
A few more suggestions:
- [ ] Label the y-axis of the signals in Figure 1
- [ ] Include some discussion about the potential scientific interest of the "box" signals.  Some of these could very well be secondary eclipses of WDs, that would be super-easy to find with a very modest level of RV follow-up! For how many signals is the box model is the best explanation?  These might even be worth a separate table.
- [ ] Label the units of the y-axis (at least in the first column) in Figure 3.
- [ ] In the OR section (or conclusion), mention/discuss the implied integrated occurrence rate over the two bins---something like 1.5-2 planets per star?  This is interesting because (a) the Solar System has 2, and (b) it maybe jives with microlensing searches finding lots of sub-Jupiters on longer periods (would need to check references for this)?  This is good to connect with because most people don't have intuition for a differential rate in log units.
- [ ] Table 6 should also have the epoch, as well as the period, for observers' convenience.

**Comment by dfm** [comment]
Thanks. Added to the list.

**Comment by ericagol** [comment]
The square ones would be worth searching for candidate microlensing events.

Eric Agol
Astronomy Professor
University of Washington

**Comment by timothydmorton** [comment]
Are there even any known non-astrophysical effects in the data that will create square signals?  If not, these are all of interest.

**Comment by dfm** [comment]
The vast majority are non-physical. A box + GP can fit a lot of things!

**Comment by dfm** [comment]
I think that it's opening a whole can of worms to go down the path of trying to understand the distribution of non-transit signals and I'm really not set up to do that right now. Perhaps Figure 1 is misleading because most signals that are best fit by the box don't look quite so distinctly box-shaped! It's just there to pick up the garbage that lights up the filter but isn't sufficiently transit-like to warrant the extra parameters. I think that a more careful job would have to be done to try to get a sample to follow up.

**Comment by timothydmorton** [comment]
Fair enough.  Are there at least a few large SNR box signals that are sitting in a table somewhere that you could point out?  No need to do anything comprehensive/systematic...
