### ISSUE TITLE
Is there a depth cut in your automated vetting?

### ISSUE THREAD

**Issue by timothydmorton** [dfm/peerless#14]
i.e., do you reject any transit/eclipse-like signals due to them having very large, obviously EB-like depths?

**Comment by dfm** [comment]
There isn't but I do have an impact parameter cut that will remove anything that looks V-shaped. Also, the completeness does seem to go down for very deep transits. I expect that this is mostly caused by the fact that I optimized my GP model for finding smaller transits but I'm not exactly sure.

**Comment by timothydmorton** [comment]
Ok I should add some more discussion about this (to explain why there
aren't more EBs). Any idea how many signals you reject due to V-ness?

**Comment by dfm** [comment]
Yeah. Good idea.

I reject 2 candidates with the centroid offset test (these are both probably BEBs) and 7 candidates with the impact parameter cut (these ones are also probably astrophysical).

If I'm honest, one of the main reasons why I added the impact parameter cut was because it was a pain the in the ass to get the MCMC fits to converge on those candidates :-) but we could consider putting a table in with at least the transit times and depths for these candidates.

**Comment by dfm** [comment]
Also: two of these rejections are actually for the same system so I was double counting in that case. Only 6 systems were rejected by the vness cut.

**Comment by dfm** [comment]
Oops. One more mistake there. Those numbers were old, some of these were already found in the new EB catalog. After removing those, 1 candidate was rejected for the centroid motion and 3 were rejected for being V-shaped.

The real reason why there aren't very many EBs is because the recent catalog includes a table of long period EBs with only 1 or 2 eclipses and I removed all of those from the target list.

**Comment by dfm** [comment]
Reference: http://adsabs.harvard.edu/abs/2016AJ....151...68K

Look... Eric is an author :-)

**Comment by ericagol** [comment]
Yeah - I helped to find a bunch of heartbeat stars for that catalog....   Is this something you find as well?

Eric Agol
Astronomy Professor
University of Washington

**Comment by ericagol** [comment]
I can't remember where I heard this idea, but someone suggested chopping each transit in half & fitting the first & second halves separately  to see if you get the same parameters for both.  This can help flag asymmetry for vetting.

Eric Agol
Astronomy Professor
University of Washington
