### ISSUE TITLE
Referee: Circular argument for rate of long period EBs?

### ISSUE THREAD

**Issue by dfm** [dfm/peerless#27]
In the referee's comments, they say:

> In the first paragraph of Section 3.1, it is mentioned that the light
> curves of known EBs and other known false positives are excluded from the
> analysis. What would happen if these were left in the sample? Also, later in
> the paper (Section 7), you use the detected Kepler EBs to estimate the number
> of EB signals you should expect to see in your analysis. It does not seem like
> you took into account the fact that you had already removed a large sample of
> the known EBs prior to the analysis (which would then serve to decrease the
> number of EB signals you should expect to detect).

@timothydmorton do you have any comments about this? I can probably write something but anything would help.

**Comment by timothydmorton** [comment]
This is actually a good point that I missed.  When I calibrate the binary star population parameters using the Kepler EB detections, I try to roughly match the number and period distribution of Kepler EBs with P < 1000d.  However, when predicting the number of EBs _we_ should see in _our_ search, I should take into account that you have excluded from the search the known Kepler EBs, which include, e.g., 10 systems with periods > 1000d, presumably most of which are likely single or double eclipses.

The complication with trying to correct for this is that my query to count "detected" EBs in my simulated sample is the following: 

``` python
dfm_q = 'n_pri < 3 and n_sec < 3 and ' +\
        '(((n_pri==0 or snr_pri < 15) and snr_sec > 15) or ' +\
        '((n_sec==0 or snr_sec < 15)  and snr_pri > 15))'
dfm_q += ' and ((T14_pri < 2.5 and n_pri > 0) or (T14_sec < 2.5 and n_sec > 0))'
```

That is, I require there to be a primary XOR a secondary (showing both a detectable primary and secondary will exclude a detection), as well as < 3 of whichever it is.  So in order to properly account for how many previously identified Kepler EBs should go into my count as "already detected before our search," I need to know how many of the catalogued Kepler EBs pass this query.  It would be nice if both a primary & secondary were required to get in the Kepler EB catalog, but this is likely not the case...  I'll skim the Kepler EB docs/papers to see if I can figure this out (doesn't seem like the catalog columns contain enough info to answer this question).

**Comment by dfm** [comment]
Yeah... the catalog that I used was [Kirk et al.](http://adsabs.harvard.edu/abs/2016AJ....151...68K) and the selection function is definitely a little complicated. I don't think that we need to do anything too drastic. We should just have some argument about the order of magnitude of this effect.

**Comment by timothydmorton** [comment]
OK... so then the gist of this issue that by assuming (in effect) that all of the Kepler EBs that we have excluded from our search have either at least 3 eclipses _or_ a primary and a secondary, we are slightly overpredicting the number of EBs that should be in our sample.  If we were to correct for this effect, our number of predicted EBs in our sample should decrease by a few.  But focusing on the effect on FPPs (the whole point of this exercise), ignoring this effect will cause us to _overestimate_ FPP, which is a conservative thing to do.  Do you want me to put something in the ref response and/or document to this effect?

**Comment by dfm** [comment]
Yeah. I think that that would be sufficient. If you don't mind trying to draft something, that would be awesome! Thanks!

**Comment by timothydmorton** [comment]
Done.  Added a paragraph to the end of S7, and a note in the ref response.

**Comment by dfm** [comment]
I think that there is one other point. If the light curves or population of EBs that we remove from the sample are qualitatively different from the ones left over then there might be a problem too. Let me think about this and draft something to say cause I'm not even making sense to myself right now...
