### ISSUE TITLE
power-law occ. rate parameters?

### ISSUE THREAD

**Issue by timothydmorton** [dfm/peerless#6]
When you fit the Burke-style double-plaw occurrence rate, what are the best-fit parameters?  I guess they probably won't be very well-constrained, but I just need something sensible/justified for my simulations of the shape distribution.

**Comment by dfm** [comment]
The fit was done in this notebook: https://github.com/dfm/peerless/blob/master/document/figures/burkeish.ipynb

Some of the text is old but the code should be correct. The model is:

```
def population_model(theta, period, rp):
    lnf0, beta, alpha = theta
    v = np.exp(lnf0) * np.ones_like(period)
    for x, rng, n in zip((period, rp),
                         (period_rng, rp_rng),
                         (beta, alpha)):
        n1 = n + 1
        v *= x**n*n1 / (rng[1]**n1-rng[0]**n1)
    return v
```

where `period_rng = (50, 300)` and `rp_rng = (0.1 * 10.864, 10.864)` and the maximum likelihood parameters are `theta = np.array([-0.21966917, -0.66251643, -2.44605275])`.

I definitely wouldn't take these numbers super seriously because more care should be taken to do it properly but it should be roughly reasonable.

**Comment by timothydmorton** [comment]
Did you not fit the double power-law between 2 and 25 years, as well as the two-bin model?  I need to simulate the long-period planets (not 50-300d) for the EB/BEB/planet shape comparison.

**Comment by timothydmorton** [comment]
Never mind about this, now I'm just simulating the two-bin model, which makes more sense anyway.
